"""empty message

Revision ID: 2754fe80788a
Revises: 
Create Date: 2019-04-05 12:52:58.458652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2754fe80788a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_name', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cover_image', sa.String(length=64), nullable=True),
    sa.Column('subtitle', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('f_nf', sa.String(length=12), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=64), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('book_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('update_news', sa.Text(), nullable=False),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Text(), nullable=False),
    sa.Column('diastole', sa.Text(), nullable=False),
    sa.Column('systole', sa.Text(), nullable=False),
    sa.Column('bicep', sa.Text(), nullable=False),
    sa.Column('chest', sa.Text(), nullable=False),
    sa.Column('health_name', sa.Text(), nullable=False),
    sa.Column('stomach', sa.Text(), nullable=False),
    sa.Column('waist', sa.Text(), nullable=False),
    sa.Column('hips', sa.Text(), nullable=False),
    sa.Column('progress_image', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('area', sa.String(length=160), nullable=True),
    sa.Column('resolution', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('news')
    op.drop_table('health')
    op.drop_table('goal')
    op.drop_table('book')
    op.drop_table('blog')
    # ### end Alembic commands ###
